### ISSUE TITLE
Projektmanagement & Dokumentation

### ISSUE THREAD

**Issue by makl9797** [makl9797/forschungsprojekt-ccc#1]
### Beschreibung
Es werden Issues, Milestones und Pflege für das Github Repo benötigt um die Informationen die man sammelt und die Anwendung die man umsetzt an einem Punkt zu speichern. 

### ToDo 

- [x] Wiki aufräumen
- [x] Issues anlegen und zuweisen
- [x] Milestone(s) anlegen
- [x] Informationen aus den Meetings sammeln
  - [x] Aufteilung
  - [x] Aufgaben (in Issues verlagern)
  - [x] Meetingplan ("Kalender)
